language: node_js
node_js:
  - "4.2.4"
addons:
  code_climate:
    repo_token:

before_script:
  - npm install -g gulp
  - npm install -g istanbul

script: gulp build

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info